(() => {
 const $=s=>document.querySelector(s), cfg=window.YUNG_SUPABASE_CONFIG;
 const loginPanel=$('#login-panel'),dashboard=$('#dashboard'),loginMsg=$('#login-msg');
 if(!window.supabase||!cfg?.url||!cfg?.anonKey){loginMsg.textContent='Configura Supabase in supabase-config.js.';return;}
 const client=window.supabase.createClient(cfg.url,cfg.anonKey);
 async function uploadImage(file,folder){
  if(!file||!file.size)return null;
  if(!file.type.startsWith('image/'))throw new Error('Seleziona un file immagine.');
  if(file.size>5*1024*1024)throw new Error('L’immagine supera il limite di 5 MB.');
  const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';
  const path=folder+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,9)+'.'+ext;
  const {error}=await client.storage.from('site-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});
  if(error)throw error;
  return client.storage.from('site-images').getPublicUrl(path).data.publicUrl;
 }

 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const isoInput=v=>v?new Date(v).toISOString().slice(0,16):'';
 const isoValue=v=>v?new Date(v).toISOString():null;
 const msg=(id,t)=>$('#'+id).textContent=t;
 const errText=e=>e?.message||e?.details||'Errore sconosciuto';
 async function session(){const {data}=await client.auth.getSession();const yes=!!data.session;loginPanel.classList.toggle('hidden',yes);dashboard.classList.toggle('hidden',!yes);if(yes){loadNews();loadStaff();loadSocial();}}
 $('#login-form').addEventListener('submit',async e=>{e.preventDefault();msg('login-msg','Accesso in corso…');const f=new FormData(e.currentTarget);const {error}=await client.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});msg('login-msg',error?'Accesso fallito: '+errText(error):'');await session();});
 $('#logout').addEventListener('click',async()=>{await client.auth.signOut();await session();});
 function reset(formId,headingId,title){$(formId).reset();$(formId).elements.id.value='';if(headingId)$(headingId).textContent=title;}
 $('#cancel-news').onclick=()=>{reset('#news-form','#news-heading','Pubblica una news');msg('news-msg','');};
 $('#cancel-staff').onclick=()=>{reset('#staff-form','#staff-heading','Aggiungi membro dello staff');msg('staff-msg','');};
 $('#cancel-social').onclick=()=>{reset('#social-form','#social-heading','Aggiungi social');msg('social-msg','');};
 async function loadNews(){
  const box=$('#news-list');box.textContent='Caricamento…';
  const {data,error}=await client.from('news').select('*').order('created_at',{ascending:false});
  if(error){box.textContent='Errore lettura news: '+errText(error);return;}
  if(!data?.length){box.textContent='Nessuna news presente.';return;}
  box.innerHTML=data.map(n=>'<div class="admin-item"><div><strong>'+esc(n.title)+'</strong><p>'+esc(n.category)+' · '+esc(n.status)+(n.expires_at?' · scade '+esc(new Date(n.expires_at).toLocaleString('it-IT')):' · senza scadenza')+'</p></div><div class="admin-actions"><button class="button button-ghost" data-edit-news="'+n.id+'">MODIFICA</button><button class="button button-ghost" data-del-news="'+n.id+'">ELIMINA</button></div></div>').join('');
  box.querySelectorAll('[data-edit-news]').forEach(b=>b.onclick=()=>{const n=data.find(x=>String(x.id)===b.dataset.editNews);const f=$('#news-form');for(const k of ['id','title','category','status','summary','content','image_url'])f.elements[k].value=n[k]??'';f.elements.published_at.value=isoInput(n.published_at);f.elements.expires_at.value=isoInput(n.expires_at);$('#news-heading').textContent='Modifica news';$('#news-admin').scrollIntoView({behavior:'smooth'});});
  box.querySelectorAll('[data-del-news]').forEach(b=>b.onclick=async()=>{const n=data.find(x=>String(x.id)===b.dataset.delNews);if(!confirm('Eliminare definitivamente la news “'+n.title+'”?'))return;msg('news-msg','Eliminazione in corso…');const {error}=await client.from('news').delete().eq('id',n.id);msg('news-msg',error?'Eliminazione non riuscita: '+errText(error):'News eliminata.');await loadNews();});
 }
 $('#news-form').addEventListener('submit',async e=>{e.preventDefault();msg('news-msg','Salvataggio…');const f=e.currentTarget,d=new FormData(f),id=d.get('id');let imageUrl=String(d.get('image_url')||'').trim()||null;try{const uploaded=await uploadImage(d.get('image_file'),'news');if(uploaded)imageUrl=uploaded;}catch(error){msg('news-msg','Errore caricamento immagine: '+errText(error));return;}const row={title:String(d.get('title')).trim(),category:d.get('category'),status:d.get('status'),summary:String(d.get('summary')).trim(),content:String(d.get('content')||'').trim(),image_url:imageUrl,published_at:isoValue(d.get('published_at'))||(d.get('status')==='published'?new Date().toISOString():null),expires_at:isoValue(d.get('expires_at')),updated_at:new Date().toISOString()};const {error}=id?await client.from('news').update(row).eq('id',id):await client.from('news').insert(row);if(error){msg('news-msg','Errore: '+errText(error));return;}msg('news-msg','News salvata correttamente.');reset('#news-form','#news-heading','Pubblica una news');await loadNews();});
 async function loadStaff(){const box=$('#staff-list');const {data,error}=await client.from('staff_members').select('*').order('sort_order').order('id');if(error){box.textContent='Errore staff: '+errText(error)+' — esegui lo schema SQL aggiornato.';return;}if(!data?.length){box.textContent='Nessun membro ancora. Aggiungine uno qui sopra.';return;}box.innerHTML=data.map(n=>'<div class="admin-item"><div><strong>'+esc(n.name)+'</strong><p>'+esc(n.role)+' · '+(n.active?'visibile':'nascosto')+'</p></div><div class="admin-actions"><button class="button button-ghost" data-edit-staff="'+n.id+'">MODIFICA</button><button class="button button-ghost" data-del-staff="'+n.id+'">ELIMINA</button></div></div>').join('');box.querySelectorAll('[data-edit-staff]').forEach(b=>b.onclick=()=>{const n=data.find(x=>String(x.id)===b.dataset.editStaff),f=$('#staff-form');for(const k of ['id','name','role','bio','initials','avatar_url','sort_order'])f.elements[k].value=n[k]??'';f.elements.active.value=String(n.active);$('#staff-heading').textContent='Modifica membro';$('#staff-admin').scrollIntoView({behavior:'smooth'});});box.querySelectorAll('[data-del-staff]').forEach(b=>b.onclick=async()=>{const n=data.find(x=>String(x.id)===b.dataset.delStaff);if(!confirm('Eliminare '+n.name+'?'))return;const {error}=await client.from('staff_members').delete().eq('id',n.id);msg('staff-msg',error?'Errore: '+errText(error):'Membro eliminato.');await loadStaff();});}
 $('#staff-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),id=d.get('id');msg('staff-msg','Salvataggio…');let avatarUrl=d.get('avatar_url').trim()||null;try{const uploaded=await uploadImage(d.get('avatar_file'),'staff');if(uploaded)avatarUrl=uploaded;}catch(error){msg('staff-msg','Errore caricamento immagine: '+errText(error));return;}const row={name:d.get('name').trim(),role:d.get('role').trim(),bio:d.get('bio').trim(),initials:d.get('initials').trim()||d.get('name').trim().slice(0,2).toUpperCase(),avatar_url:avatarUrl,sort_order:Number(d.get('sort_order')||0),active:d.get('active')==='true'};const {error}=id?await client.from('staff_members').update(row).eq('id',id):await client.from('staff_members').insert(row);if(error){msg('staff-msg','Errore: '+errText(error));return;}msg('staff-msg','Membro salvato.');reset('#staff-form','#staff-heading','Aggiungi membro dello staff');await loadStaff();});
 async function loadSocial(){const box=$('#social-list');const {data,error}=await client.from('social_links').select('*').order('sort_order').order('id');if(error){box.textContent='Errore social: '+errText(error)+' — esegui lo schema SQL aggiornato.';return;}if(!data?.length){box.textContent='Nessun social inserito. Aggiungi Instagram, TikTok, YouTube ecc.';return;}box.innerHTML=data.map(n=>'<div class="admin-item"><div><strong>'+esc(n.label)+'</strong><p>'+esc(n.url)+' · '+(n.active?'visibile':'nascosto')+'</p></div><div class="admin-actions"><button class="button button-ghost" data-edit-social="'+n.id+'">MODIFICA</button><button class="button button-ghost" data-del-social="'+n.id+'">ELIMINA</button></div></div>').join('');box.querySelectorAll('[data-edit-social]').forEach(b=>b.onclick=()=>{const n=data.find(x=>String(x.id)===b.dataset.editSocial),f=$('#social-form');for(const k of ['id','label','url','sort_order'])f.elements[k].value=n[k]??'';f.elements.active.value=String(n.active);$('#social-heading').textContent='Modifica social';$('#social-admin').scrollIntoView({behavior:'smooth'});});box.querySelectorAll('[data-del-social]').forEach(b=>b.onclick=async()=>{const n=data.find(x=>String(x.id)===b.dataset.delSocial);if(!confirm('Eliminare il link '+n.label+'?'))return;const {error}=await client.from('social_links').delete().eq('id',n.id);msg('social-msg',error?'Errore: '+errText(error):'Link eliminato.');await loadSocial();});}
 $('#social-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),id=d.get('id');msg('social-msg','Salvataggio…');const row={label:d.get('label').trim(),url:d.get('url').trim(),sort_order:Number(d.get('sort_order')||0),active:d.get('active')==='true'};const {error}=id?await client.from('social_links').update(row).eq('id',id):await client.from('social_links').insert(row);if(error){msg('social-msg','Errore: '+errText(error));return;}msg('social-msg','Link social salvato.');reset('#social-form','#social-heading','Aggiungi social');await loadSocial();});
 client.auth.onAuthStateChange(()=>{setTimeout(session,0);});session();
})();