(() => {
 const cfg=window.YUNG_SUPABASE_CONFIG; const $=s=>document.querySelector(s);
 const loginPanel=$('#login-panel'), dashboard=$('#dashboard'), loginMsg=$('#login-msg'), formMsg=$('#form-msg'), listMsg=$('#list-msg'), form=$('#news-form'), list=$('#news-list'); let client=null;
 if(!window.supabase||!cfg||!cfg.url||cfg.url.startsWith('INSERISCI_')||!cfg.anonKey||cfg.anonKey.startsWith('INSERISCI_')){loginMsg.textContent='Configura URL e chiave anon di Supabase in supabase-config.js.';$('#login-form').addEventListener('submit',e=>e.preventDefault());return;}
 client=window.supabase.createClient(cfg.url,cfg.anonKey);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function showSession(){const {data}=await client.auth.getSession();const session=data.session;loginPanel.classList.toggle('hidden',!!session);dashboard.classList.toggle('hidden',!session);if(session)loadList();}
 $('#login-form').addEventListener('submit',async e=>{e.preventDefault();loginMsg.textContent='Accesso in corso…';const fd=new FormData(e.currentTarget);const {error}=await client.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});loginMsg.textContent=error?'Accesso non riuscito. Verifica credenziali e autorizzazioni.':'';await showSession();});
 $('#logout').addEventListener('click',async()=>{await client.auth.signOut();form.reset();await showSession();});
 function resetForm(){form.reset();form.elements.id.value='';$('#form-heading').textContent='Pubblica una news';formMsg.textContent='';}
 $('#cancel-edit').addEventListener('click',resetForm);
 form.addEventListener('submit',async e=>{e.preventDefault();formMsg.textContent='Salvataggio…';const fd=new FormData(form);const id=fd.get('id');const row={title:String(fd.get('title')).trim(),category:fd.get('category'),status:fd.get('status'),summary:String(fd.get('summary')).trim(),content:String(fd.get('content')||'').trim(),image_url:String(fd.get('image_url')||'').trim()||null,updated_at:new Date().toISOString()};if(row.status==='published'&&!id)row.published_at=new Date().toISOString();const result=id?await client.from('news').update(row).eq('id',id):await client.from('news').insert(row);if(result.error){formMsg.textContent='Errore nel salvataggio. Verifica la configurazione SQL e i permessi admin.';return;}formMsg.textContent='News salvata.';resetForm();await loadList();});
 async function loadList(){list.textContent='Caricamento…';const {data,error}=await client.from('news').select('id,title,category,status,published_at,summary,content,image_url').order('created_at',{ascending:false});if(error){list.textContent='Impossibile leggere le news: verifica la tabella e i permessi admin.';return;}if(!data.length){list.textContent='Ancora nessuna news.';return;}list.innerHTML=data.map(n=>'<div class="admin-item"><div><strong>'+esc(n.title)+'</strong><p>'+esc(n.category)+' · '+esc(n.status)+'</p></div><div class="admin-actions"><button class="button button-ghost" data-edit="'+esc(n.id)+'" type="button">MODIFICA</button><button class="button button-ghost" data-delete="'+esc(n.id)+'" type="button">ELIMINA</button></div></div>').join('');list.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{const n=data.find(x=>x.id===b.dataset.edit);if(!n)return;for(const k of ['id','title','category','status','summary','content','image_url'])form.elements[k].value=n[k]??'';$('#form-heading').textContent='Modifica news';formMsg.textContent='';window.scrollTo({top:0,behavior:'smooth'});}));list.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{const n=data.find(x=>x.id===b.dataset.delete);if(!n||!confirm('Eliminare la news “'+n.title+'”?'))return;const {error}=await client.from('news').delete().eq('id',n.id);listMsg.textContent=error?'Eliminazione non riuscita. Verifica i permessi.':'News eliminata.';await loadList();}));}
 client.auth.onAuthStateChange(()=>showSession());showSession();
})();
