(() => {
 const grid=document.getElementById('news-grid'),status=document.getElementById('news-status'),cfg=window.YUNG_SUPABASE_CONFIG;
 if(!grid||!window.supabase||!cfg?.url||!cfg?.anonKey){if(grid)grid.innerHTML='<p class="edit-note">News non disponibili: controlla la configurazione.</p>';return;}
 const client=window.supabase.createClient(cfg.url,cfg.anonKey);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const dateLabel=v=>v?new Date(v).toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'}):'';
 const modal=document.createElement('div');modal.className='news-modal';modal.hidden=true;modal.innerHTML='<div class="news-modal-backdrop" data-close-news></div><section class="news-modal-panel" role="dialog" aria-modal="true" aria-labelledby="news-modal-title"><button type="button" class="news-modal-close" aria-label="Chiudi" data-close-news>×</button><div class="news-modal-content"></div></section>';document.body.appendChild(modal);
 const closeModal=()=>{modal.hidden=true;document.body.style.overflow='';};modal.querySelectorAll('[data-close-news]').forEach(b=>b.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
 async function loadNews(){
  const {data,error}=await client.from('news').select('id,title,summary,content,category,image_url,published_at,expires_at').eq('status','published').order('published_at',{ascending:false}).limit(30);
  if(error){grid.innerHTML='<p class="edit-note">Non è stato possibile caricare le news. Verifica la configurazione SQL.</p>';if(status)status.textContent='Feed temporaneamente non disponibile.';return;}
  const now=Date.now(),items=(data||[]).filter(n=>!n.expires_at||new Date(n.expires_at).getTime()>now).slice(0,6);window.__yungNewsItems=items;
  if(!items.length){grid.innerHTML='<p class="edit-note">Nessuna news pubblicata al momento. Torna presto!</p>';if(status)status.textContent='';return;}
  grid.innerHTML=items.map((n,i)=>{const image=n.image_url?'<img src="'+esc(n.image_url)+'" alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover;position:absolute;inset:0">':'';return '<article tabindex="0" role="button" data-news-id="'+esc(n.id)+'" class="news-card reveal visible news-card-clickable"><div class="news-visual news-visual-'+['one','two','three'][i%3]+'" style="position:relative;overflow:hidden">'+image+'<span class="news-category">'+esc(n.category||'COMMUNITY')+'</span><span class="visual-glyph" aria-hidden="true">'+['✳','⌖','◉'][i%3]+'</span><span class="visual-code">YUNG NETWORK / NEWS</span></div><div class="news-body"><div class="news-meta"><span>'+esc(n.category||'NEWS')+'</span><span class="news-date">'+esc(dateLabel(n.published_at))+'</span></div><h3>'+esc(n.title)+'</h3><p>'+esc(n.summary||n.content||'')+'</p><span class="news-read-more">LEGGI TUTTO ↗</span></div></article>';}).join('');
  if(status)status.textContent='Ultimi aggiornamenti del network.';
 }
 grid.addEventListener('click',e=>{const card=e.target.closest('[data-news-id]');if(card)openNews(card.dataset.newsId);});
 grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-news-id]')){e.preventDefault();openNews(e.target.dataset.newsId);}});
 function openNews(id){const n=(window.__yungNewsItems||[]).find(item=>String(item.id)===String(id));if(!n)return;const content=modal.querySelector('.news-modal-content');content.innerHTML=(n.image_url?'<img class="news-modal-image" src="'+esc(n.image_url)+'" alt="">':'')+'<div class="news-meta"><span>'+esc(n.category||'NEWS')+'</span><span class="news-date">'+esc(dateLabel(n.published_at))+'</span></div><h2 id="news-modal-title">'+esc(n.title)+'</h2><p class="news-modal-summary">'+esc(n.summary||'')+'</p><div class="news-modal-text">'+esc(n.content||n.summary||'').replace(/\n/g,'<br>')+'</div>';modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('.news-modal-close').focus();}
 loadNews();
})();