-- Yung Network: schema iniziale per le news (Supabase SQL Editor)
-- Esegui questo script nel progetto Supabase prima di configurare il pannello.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  summary text not null default '',
  content text not null default '',
  category text not null default 'Community',
  image_url text,
  status text not null default 'draft' check (status in ('draft','published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
alter table public.news enable row level security;
drop policy if exists "Admins can read own admin record" on public.admin_users;
create policy "Admins can read own admin record" on public.admin_users for select to authenticated using (user_id = auth.uid());
drop policy if exists "Anyone can read published news" on public.news;
create policy "Anyone can read published news" on public.news for select to anon, authenticated using (status = 'published' or exists (select 1 from public.admin_users where admin_users.user_id = auth.uid()));
drop policy if exists "Admins can insert news" on public.news;
create policy "Admins can insert news" on public.news for insert to authenticated with check (exists (select 1 from public.admin_users where admin_users.user_id = auth.uid()));
drop policy if exists "Admins can update news" on public.news;
create policy "Admins can update news" on public.news for update to authenticated using (exists (select 1 from public.admin_users where admin_users.user_id = auth.uid())) with check (exists (select 1 from public.admin_users where admin_users.user_id = auth.uid()));
drop policy if exists "Admins can delete news" on public.news;
create policy "Admins can delete news" on public.news for delete to authenticated using (exists (select 1 from public.admin_users where admin_users.user_id = auth.uid()));
grant select on public.news to anon, authenticated;
grant insert, update, delete on public.news to authenticated;
grant select on public.admin_users to authenticated;
-- Dopo aver creato il tuo utente in Supabase Authentication, rendilo admin eseguendo:
-- insert into public.admin_users (user_id) values ('INCOLLA-QUI-UUID-UTENTE');
-- Non inserire mai la service_role key nel sito. Usa solo la anon/publishable key con RLS attivo.
